### ISSUE TITLE
Error  installation failed

### ISSUE THREAD

**Issue by slave-but-free** [mway-io/Espresso#106]
Hello

i  followed the installation steps  on my mac, i created an alias to the espresso path, but when i try 
espresso version 
or any other command i get :

module.js:340
    throw err;
          ^
Error: Cannot find module 'step'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/Unik/mobile-apps/the-m-project/Espresso/core/e.js:64:25)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

**Comment by dominiklaubach** [comment]
Hi slave-but-free,

did you install Espresso via GitHub, via NPM or simply download the prepackaged ZIP from the website? What version of OSX are you running on? What version of Node did you install?

Best regards
Dominik

**Comment by slave-but-free** [comment]
Hi Dominik,
Thanks for your interest,  i'm running on Mac OS X Snow Leopard 10.6.8 , i installed Espresso via GitHub,for Node i installed node-v0.8.3.pkg form their website.
i have a mobile project ongoing with phonegap ,and i think that your tool is what i need.
Best regards .

**Comment by dominiklaubach** [comment]
Hi slave-but-free,

ok, did you install the git submodules correctly?

```
git clone git://github.com/mwaylabs/Espresso.git
git submodule update --init
```

**Comment by slave-but-free** [comment]
Hi Dominik , It works  !
the error i've made the first time is that i did "git submodule update --init" but not in Espresso directory.
Awesome thanks a lot,
