### ISSUE TITLE
espresso -d path not working

### ISSUE THREAD

**Issue by hano** [mway-io/Espresso#50]
my espresso version:
$ espresso version
Espresso 0.8.0

my node version:
$ node -v
v0.6.0

this is what i've done:
$ cd /tmp

$ espresso init -p MinusDTest
Project successfully generated!

$ espresso server -d /tmp/MinusDTest/
raises this error:
The "sys" module is now called "util". It should have a similar interface.
LOG: Server running at http://127.0.0.1:8000/MinusDTest
Building application: "MinusDTest"
Building components:
calling build() for: "MinusDTest_App"
calling build() for: "MinusDTest_AppResources"
calling build() for: "core"
calling build() for: "ui"
calling build() for: "jquery"
calling build() for: "underscore"
calling build() for: "themes"
calling build() for: "tmp_themes"
calling build() for: "bootstrapping"
calling build() for: "jquery_mobile_plugins"
calling build() for: "jquery_mobile"
underscore: done
bootstrapping: done
tmp_themes: done
MinusDTest_AppResources: done
jquery_mobile_plugins: done
ui: done
jquery: done
jquery_mobile: done
core: done

/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:38
        throw arguments[0];
                       ^
TypeError: Cannot read property 'dependencyTrees' of undefined
    at Function.sortDependencies (/Users/mway/Documents/mway/themproject/Espresso/tasks/task_dependency.js:270:15)
    at next (/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:51:23)
    at next (/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:54:7)
    at next (/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:54:7)
    at next (/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:60:7)
    at [object Object].Step [as sequencer](/Users/mway/Documents/mway/themproject/Espresso/node_modules/step/lib/step.js:124:3)
    at [object Object].duty (/Users/mway/Documents/mway/themproject/Espresso/tasks/task_dependency.js:64:8)
    at [object Object].run (/Users/mway/Documents/mway/themproject/Espresso/tasks/task.js:52:10)
    at /Users/mway/Documents/mway/themproject/Espresso/tasks/task.js:62:19
    at [object Object].duty (/Users/mway/Documents/mway/themproject/Espresso/tasks/task_preSort.js:74:5)

**Comment by yoyo20211** [comment]
I also got this issue. I'm still waiting for the answer.

Thanks you

**Comment by hano** [comment]
I just tested it successfully on the Detox branch.
espresso version
Espresso 1.1.0
node -v
v0.6.13
